filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
    multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    multiline.negate: true
    multiline.match: after
output:
  logstash:
    hosts: ["logstash:5044"]
    username: "elastic"
    password: "changeme"
#  elasticsearch:
#    hosts: ["elasticsearch:9200"]
#    username: "elastic"
#    password: "changeme"